```javascript
// pages/index.js
import Head from 'next/head';
export default function Home() {
  return (
    <div>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, world!</h1>
      <p>This is a Next.js application.</p>
    </div>
  );
}
```